
CREATE TABLE EVENT_CATEGORIES
(
    EventCategoryID INT IDENTITY(1,1) NOT NULL,
    EventID INT NOT NULL,
    CategoryID INT NOT NULL,
    EntryFee DECIMAL(10,2) NOT NULL,
    MaximumParticipants INT NOT NULL,

    CONSTRAINT PK_EVENT_CATEGORIES
        PRIMARY KEY (EventCategoryID),

    CONSTRAINT UQ_EVENT_CATEGORIES_Event_Category
        UNIQUE (EventID, CategoryID),

    CONSTRAINT FK_EVENT_CATEGORIES_Event
        FOREIGN KEY (EventID) REFERENCES EVENTS(EventID),

    CONSTRAINT FK_EVENT_CATEGORIES_Category
        FOREIGN KEY (CategoryID) REFERENCES CATEGORIES(CategoryID)
);