
CREATE TABLE USER_EVENTS
(
    UserEventID INT IDENTITY(1,1) NOT NULL,
    UserID INT NOT NULL,
    EventID INT NOT NULL,
    RegistrationDate DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    RaceNumber NVARCHAR(30) NOT NULL,
    Status NVARCHAR(30) NOT NULL DEFAULT 'Registered',

    CONSTRAINT PK_USER_EVENTS PRIMARY KEY (UserEventID),

    CONSTRAINT UQ_USER_EVENTS_User_Event
        UNIQUE (UserID, EventID),

    CONSTRAINT FK_USER_EVENTS_User
        FOREIGN KEY (UserID) REFERENCES USERS(UserID),

    CONSTRAINT FK_USER_EVENTS_Event
        FOREIGN KEY (EventID) REFERENCES EVENTS(EventID)
);
