
CREATE TABLE WEATHER_INFORMATION
(
    WeatherID INT IDENTITY(1,1) NOT NULL,
    EventID INT NOT NULL,
    Temperature DECIMAL(5,2) NOT NULL,
    WeatherCondition NVARCHAR(100) NOT NULL,
    WindSpeed DECIMAL(6,2) NOT NULL,
    Humidity DECIMAL(5,2) NOT NULL,
    RecordedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT PK_WEATHER_INFORMATION
        PRIMARY KEY (WeatherID),

    CONSTRAINT FK_WEATHER_Event
        FOREIGN KEY (EventID) REFERENCES EVENTS(EventID)
);