INSERT INTO USERS
(
    FirstName,
    LastName,
    Email,
    PasswordHash,
    PhoneNumber,
    Role
)
VALUES
(
    'Thabo',
    'Mokoena',
    'thabo.mokoena@raceday.co.za',
    'HASH_ORGANISER_001',
    '0825550101',
    'Organiser'
),
(
    'Lerato',
    'Dlamini',
    'lerato.dlamini@raceday.co.za',
    'HASH_ORGANISER_002',
    '0835550102',
    'Organiser'
),
(
    'Sipho',
    'Ndlovu',
    'sipho.ndlovu@example.com',
    'HASH_PARTICIPANT_001',
    '0845550103',
    'Participant'
),
(
    'Aisha',
    'Naidoo',
    'aisha.naidoo@example.com',
    'HASH_PARTICIPANT_002',
    '0855550104',
    'Participant'
);