CREATE TABLE ROUTES
(
    RouteID INT IDENTITY(1,1) NOT NULL,
    EventID INT NOT NULL,
    RouteName NVARCHAR(150) NOT NULL,
    DistanceKM DECIMAL(6,2) NOT NULL,
    ElevationGain DECIMAL(6,2) NOT NULL,
    Description NVARCHAR(500) NOT NULL,
    MapURL NVARCHAR(500) NOT NULL,

    CONSTRAINT PK_ROUTES PRIMARY KEY (RouteID),

    CONSTRAINT FK_ROUTES_Event
        FOREIGN KEY (EventID) REFERENCES EVENTS(EventID)
);