SELECT * FROM dbo.USERS;

SELECT * FROM EVENTS;

SELECT * FROM CATEGORIES;

SELECT * FROM USER_EVENTS;

SELECT * FROM EVENT_CATEGORIES;

SELECT * FROM ENROLLMENTS;

SELECT * FROM RESULTS;

SELECT * FROM ROUTES;

SELECT * FROM  WEATHER_INFORMATION;
GO